### ISSUE TITLE
able install addon on stremio but nothing result come out.

### ISSUE THREAD

**Issue by ericvlog** [nyakaspeter/stremio-torrent-stream#2]
i able the add the addon to stremio but seem something is going wrong.

if i use http://mylocalip:58827/configure it say err open media, if use localtunnel i can install it.

may i ask the stream server URL is my stremio server URL ?

because i navigate LOCALIP:8000 it says Cannot GET /

when i click movie, it will no show link from the addons.

**Comment by nyakaspeter** [comment]
Hi, if you're trying to install/use the addon on anything other than the machine hosting the addon you'll have to use a HTTPS URL that's why it only worked with localtunnel. I updated the README about this.

You'll have to run [Torrent Stream Server](https://github.com/nyakaspeter/torrent-stream-server) on the same network or machine where you run the addon server. I've yet to write any documentation for that sorry. The stream server URL is http://HOSTIP:PORT where HOSTIP is the LAN IP of the host and PORT is the port where the Torrent Stream Server is listening, by default 8000. If you're not on nCore or iTorrent at the moment (these are Hungarian torrent sites) you'll also have to run Jackett to get results.

Stremio is only sending imdb IDs of movies and shows when searching so the torrent sites you configure in Jackett have to support searching by that, otherwise you'll also have to enable the 'Use titles for torrent search' option which may or may not work well currently.

In the future I'll probably support some popular public trackers like YTS and EZTV to be able to show more results without needing Jackett.

**Comment by ericvlog** [comment]
ok, i will try it later on, any thanks for your kind reply!!

thanks
